---
rbac:
  create: true
  apiVersion: v1beta1
  serviceAccountName: vault-etcd-sa

image:
  source: "quay.io/coreos/etcd"
  tag: "v3.2.10"
  pullPolicy: "Always"

service:
  name: etcdvault
  peerPort: 2380
  clientPort: 2379
  replicas: 3
  cpu: "100m"
  memory: "512Mi"
  dataDir: "/ephemeral"
  terminationGracePeriodSeconds: 30
  tls:
    enable: false
    serverSecret:
      name: etcd-server-tls
      path: "/etcd/certs/server"
    peerSecret:
      name: etcd-peer-tls
      path: "/etcd/certs/peer"
    clientSecret:
      name: etcd-client-tls
      path: "/etcd/certs/client"

nodeSelector: {}

storage:
  storageClass: "gp2"
  size: 1Gi
  mount: "ephemeral"
  accessModes:
    - ReadWriteOnce
