component: "etcd"

rbac:
  create: true
  apiVersion: v1beta1

image:
  source: "quay.io/coreos/etcd"
  tag: "v3.2.9"
  pullPolicy: "Always"

service:
  name: etcdvault
  peerPort: 2380
  clientPort: 2379
  replicas: 3
  cpu: "100m"
  memory: "512Mi"
  dataDir: "/ephemeral"
  terminationGracePeriodSeconds: 30

nodeSelector: {}

storage:
  storageClass: "default"
  size: 1Gi
  mount: "ephemeral"
  accessModes:
    - ReadWriteOnce
