---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.service.name | default (include "vault-etcd.fullname" . ) }}
  labels:
    app: {{ template "vault-etcd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Values.service.name | default (include "vault-etcd.fullname" . ) }}
  replicas: {{ default 3 .Values.service.replicas }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ template "vault-etcd.fullname" . }}
      labels:
        app: {{ template "vault-etcd.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.service.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "vault-etcd.fullname" . }}
        image: "{{ .Values.image.source }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.peerPort }}
          name: peer
        - containerPort: {{ .Values.service.clientPort }}
          name: client
        resources:
          requests:
            cpu: {{ .Values.service.cpu }}
            memory: {{ .Values.storage.size }}
        env:
        - name: INITIAL_CLUSTER_SIZE
          value: {{ default 3 .Values.service.replicas | quote }}
        - name: STATEFULSET_NAME
          value: {{ .Values.service.name | default (include "vault-etcd.fullname" . ) }}
        - name: DATA_DIR
          value: {{ .Values.service.dataDir | quote }}
        - name: PEER_PORT
          value: {{ .Values.service.peerPort | quote }}
        - name: CLIENT_PORT
          value: {{ .Values.service.clientPort | quote }}
        - name: TLS_ENABLED
          value: {{ .Values.service.tls.enable | quote }}
        {{- if .Values.service.tls.enable }}
        - name: CERTS_SERVER_PATH
          value: {{ .Values.service.tls.serverSecret.path | quote }}
        - name: CERTS_PEER_PATH
          value: {{ .Values.service.tls.peerSecret.path | quote }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.storage.mount }}
          mountPath: {{ .Values.service.dataDir }}
        - name: config
          mountPath: /etcd-bin/etcd-start.sh
          subPath: etcd-start.sh
          readOnly: false
        - name: config
          mountPath: /etcd-bin/lifecycle-prestop.sh
          subPath: lifecycle-prestop.sh
          readOnly: false
        {{- if .Values.service.tls.enable }}
        - name: server-tls
          mountPath: {{ .Values.service.tls.serverSecret.path }}
          readOnly: true
        - name: peer-tls
          mountPath: {{ .Values.service.tls.peerSecret.path }}
          readOnly: true
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sh"
                - "/etcd-bin/lifecycle-prestop.sh"
        command:
          - "/bin/sh"
          - "/etcd-bin/etcd-start.sh"
      volumes:
      - name: config
        configMap:
          name: {{ template "vault-etcd.fullname" . }}
      {{- if .Values.service.tls.enable }}
      - name: server-tls
        secret:
          secretName: {{ .Values.service.tls.serverSecret.name }}
      - name: peer-tls
        secret:
          secretName: {{ .Values.service.tls.peerSecret.name }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
        name: {{ .Values.storage.mount }}
    spec:
      storageClassName: "{{ .Values.storage.storageClass }}"
      accessModes:
{{ toYaml .Values.storage.accessModes | indent 8 }}
      resources:
        requests:
          storage: "{{ .Values.storage.size }}"
